spring:
  application:
    name: spring-cloud-learn-eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
---
server:
  port: 8000
spring:
  profiles: server1
eureka:
  client:
    service-url:
      #服务注册
      defaultZone: http://192.168.137.1:8001/eureka/,http://192.168.137.1:8002/eureka/
---
server:
  port: 8001
spring:
  profiles: server2
eureka:
  client:
    service-url:
      #服务注册
      defaultZone: http://192.168.137.1:8000/eureka/,http://192.168.137.1:8002/eureka/
---
server:
  port: 8002
spring:
  profiles: server3
eureka:
  client:
    service-url:
      #服务注册
      defaultZone: http://192.168.137.1:8000/eureka/,http://192.168.137.1:8001/eureka/