spring:
  application:
    name: spring-cloud-learn-eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
---
server:
  port: 8000
spring:
  profiles: server1
eureka:
  client:
    service-url:
      #服务注册
      defaultZone: http://localhost:8001/eureka/,http://localhost:8002/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
---
server:
  port: 8001
spring:
  profiles: server2
eureka:
  client:
    service-url:
      #服务注册
      defaultZone: http://localhost:8000/eureka/,http://localhost:8002/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
---
server:
  port: 8002
spring:
  profiles: server3
eureka:
  client:
    service-url:
      #服务注册
      defaultZone: http://localhost:8000/eureka/,http://localhost:8001/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}