spring:
  profiles:
    active: dev
  application:
    name: spring-cloud-learn-eureka-client
---
spring:
  profiles: dev
server:
  port: 8080
eureka:
  client:
    service-url:
      # 注册到注册中心
      defaultZone: http://192.168.137.1:8000/eureka/,http://192.168.137.1:8001/eureka/,http://192.168.137.1:8002/eureka/
    registry-fetch-interval-seconds: 10
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
management:
  endpoint:
    health:
      show-details: always
user:
  service:
    name: spring-cloud-learn-user-microservice-server-provider