spring:
  profiles: dev
  application:
    name: spring-cloud-eureka-learn-client
server:
  port: 8080
eureka:
  client:
    service-url:
      # 注册到注册中心
      defaultZone: http://192.168.137.1:8000/eureka/,http://192.168.137.1:8001/eureka/,http://192.168.137.1:8002/eureka/
