server:
  port: 7070
spring:
  profiles:
    active: dev
  application:
    name: spring-cloud-learn-gateway
---
spring:
  profiles: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    nacos:
      discovery:
        namespace: 76c05fec-31cb-4c9d-a97b-cbabbbb7c56b
        server-addr: 192.168.137.100:8848,192.168.137.100:8849,192.168.137.100:8850
    sentinel:
      transport:
        dashboard: 192.168.137.100:7200
      datasource:
        ds:
          nacos:
            namespace: 03e3ff2f-712c-4876-83bb-5742b4b5893f
            server-addr: 192.168.137.100:8848,192.168.137.100:8849,192.168.137.100:8850
            dataId: gateway-sentinel.json
            groupId: ${spring.application.name}
            ruleType: flow
logging:
  level:
    org.springframework.cloud.gateway: debug
management:
  endpoint:
    health:
      show-details: always