spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: spring-cloud-learn-ribbon
server:
  port: 9000
eureka:
  client:
    service-url:
      #服务注册
      defaultZone: http://localhost:8000/eureka/,http://localhost:8001/eureka/,http://localhost:8002/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#服务提供方主机
service-provider:
  host: localhost
  #服务提供方端口
  port: 8080
  #服务提供方名称
  name: spring-cloud-learn-eureka-client