spring:
  application:
    name: nahsshan-quartz
server:
  address: www.nahsshan.com
  port: 8081
logging:
  config: classpath:logback.xml
---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://www.nahsshan.com:3306/quartz?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "123456"

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.springms: DEBUG