spring:
  profiles:
    active: dev
  application:
    name: spring-cloud-learn-user-microservice-provider
---
server:
  port: 10000
spring:
  profiles: dev
  datasource:
    url: "jdbc:mysql://192.168.137.1:3306/nahsshan?serverTimezone=UTC"
    username: "root"
    password: "123456"
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: "classpath:mapper/*.xml"