spring:
  profiles:
    active: dev
  application:
    name: spring-cloud-learn-zuul
server:
  port: 6060
---
spring:
  profiles: dev
  #配置eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/,http://localhost:8001/eureka/,http://localhost:8002/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#配置zuul路由规则 指定spring-cloud-api-client      http://localhost:6060/api-provider/* => http://localhost:802
zuul:
  routes:
    #/api-a/ 开头匹配到service-producer
    api-a:
      path: /api-a/**
      serviceId: spring-cloud-learn-eureka-client
    #/api-b/ 开头匹配到service-producer
    api-b:
      path: /api-b/**
      serviceId: service-producer
    #匹配/github/直接重定向到https://github.com/
    github:
      path: /github/**
      url: https://github.com/ZhuJunJi/spring-cloud-learn
#忽略指定服务
#zuul.ignored-services= spring-cloud-api-client

